version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: projekt-sale-db
    environment:
      POSTGRES_DB: projekt_sale
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: projekt-sale-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projekt_sale
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge